node/lib/vsotask.ts
node/test/tasklib.ts

@bryanmacfarlane .. The issue doesn't repro anymore since I am not seeing the path gets a null value anymore.. However since I have seen it before I would still recommend protecting against null.

fixing getPathInput and adding tests

---

node/test/tasklib.ts

we're expecting rmRF to fail, not succeed

fixing test

---

node/lib/task.ts
node/package.json
node/test/tasklib.ts

task changes for publish cc task

---

powershell/Tests/L0/Get-Endpoint.WritesErrorIfRequired.ps1
powershell/Tests/L0/Get-Endpoint.ps1
powershell/VstsTaskSdk/InputFunctions.ps1

I haven't updated for the node lib yet. I briefly looked into it... but the interface is a little different since it exposes separate functions to retrieve the URL vs the Auth data.

Endpoint data.

---

node/lib/task.ts
node/test/tasklib.ts

* Xplat Agent now support Code Coverage feature from Gradle task.

Gradle Task support for Code Coverage

---

node/Strings/resources.resjson/de-de/resources.resjson
node/Strings/resources.resjson/it-IT/resources.resjson
node/Strings/resources.resjson/ja-jp/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ja-jp/resources.resjson

Reverts Microsoft/vsts-task-lib#84

Revert "Update 3 loc strings."

---

node/lib/task.ts
node/package.json
node/test/tasklib.ts

Upgrade the exist function since node deprecated thae existsSync

Update File Exist Function

---

node/Strings/resources.resjson/en-US/resources.resjson
node/docs/releases.md
node/docs/vsts-task-lib.md
node/lib.json
node/task.ts
node/test/tasklib.ts

mkdirP error message improvements

---

node/mock-task.ts
node/task.ts

Adds SucceededWithIssues to the list of possible task outcomes to be in line with the PowerShell SDK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/vsts-task-lib/188)

Add support for SucceededWithIssues to node sdk

---

.vsts-ci.yml
node/docs/minagent.md

Add TFS 2017 Update 3 agent version.

---

node/docs/stepbystep.md

Deep Dive on Building Custom Build or Deploy Tasks
Please confirm this is the video that you are thinking about.  
https://youtu.be/O_34c7p4GlM?t=1173

Added video

---

node/test/dirtests.ts

Fix another broken test from timeout.

Fix timeout.

---

node/docs/docs.json
node/docs/vsts-task-lib.json
node/docs/vsts-task-lib.md
node/package-lock.json

I noticed vsts-task-lib.json had `publishTelemetry`, but that function was reverted.

Generate docs

---

node/docs/stepbystep.md
powershell/Docs/README.md

Just some low hanging fruit as I get oriented in the library.
Fixes #388 
Fixes #205

Take care of some simple doucmentation issues

---

node/README.md

ShellScript Task link updated to V2 (https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ShellScriptV2) and XCode Task link updated to V5 (https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/XcodeV5)

Fixed broken links for reference examples

---

node/test/toolrunnertests.ts
node/toolrunner.ts

initial thought for discussion.  do not merge

unc arg issue

---

node/task.ts

As proposed in #476 this are the missing commands that the NodeJs lib does not expose.

Added missing logging commands to Node lib

---

node/task.ts

Couple of small issues not caught in #477 but caught by CI, see [here](http://angularfirst.com/typescript-string-enums/) for details of what's going on in this pr

Fix issues with enum

---

node/mock-run.ts

Added setVariableName method

---

CONTRIBUTING.md
ISSUE_TEMPLATE.md
node/README.md

2 main changes:
1) Added contributing/issue-template docs - hoping this will clean up/standardize the issues/PRs we get. I feel like I'm going back and forth with people a lot before fully understanding their issue. These were mostly lifted from our other repos.
2) Updated the Node Readme. It needed cleaned up anyways and since this gets published to npmjs I thought it would be helpful to link to PowerShell documentation (as a hey, this is also available). This should also resolve #203

Updating documentation

---

node/docs/releases.md
node/vault.ts

Branch got messed up because of rebrand and me deleting my fork 🤦‍♂️ and the easiest thing to do was just create a new PR (moved from #416)
Fixes #380

Updated vault to encode secrets using cipheriv

---

node/mock-task.ts

Without these, you'll get "TypeError: no property X of undefined" in tests

Add enums to mock-task

---

node/docs/nodeVersioning.md
node/make.js
node/mock-test.ts
node/package-lock.json
node/package.json
node/test/fakeTasks/node10task/task.json
node/test/fakeTasks/node6task/task.json
node/test/mocktests.ts

This has been fixed up and should be ready for review.

Detect correct node handler

---

node/mock-task.ts
node/package.json

Add setSecret to mock-task.

---

node/mock-answer.ts
node/mock-task.ts
node/package-lock.json
node/package.json
node/test/mocktests.ts

Port for #514 from master to releases/2.8.0

Mock every exported function in task-lib.

---

tasks.schema.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/azure-pipelines-task-lib/528)

Adds Node10 and PowerShell execution handlers.

---

powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psm1

If this is something we want, we should make corresponding changes [here](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) once this is in.
Fixes #395

export write-logging command for powershell

---

node/test/toolrunnertests.ts
node/toolrunner.ts

Moved #413 here because I deleted the repo that one came from... whoops.
Fixes #277

Allow empty string in toolRunner

---

node/task.ts

Same as #414, my fork got deleted though and this is easier.
Fixes #303

Updated task variables to support dots

---

tasks.schema.json

Added:
- Groups: visibleRule
- DataSourceBindings: endpointUrl
- DataSourceBindings: resultSelector

Update tasks.schema.json for missing attributes

---

powershell/VstsTaskSdk/ServerOMFunctions.ps1

Fixes https://github.com/microsoft/azure-pipelines-task-lib/issues/580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/azure-pipelines-task-lib/594)

Resolves Newtonsoft.Json loading against 2019 version of the TFS Client OM

---

node/package.json

Added sync-request as dependency

---

node/mock-run.ts

Address some of the issue with #593

Updated to generate correct env var keys in mock task runner

---

tasks.schema.json

Adding execution options on the pre-job stage.

Adding prejobexecution

---

node/package-lock.json
node/package.json
node/task.ts
node/test/inputtests.ts

As of now, this doesn't matter because the agent does this anyways. We're adding an option to not do that from the agent and should not then enforce it here.
Agent PR - https://github.com/microsoft/azure-pipelines-agent/pull/3051
Ticket motivating this - https://developercommunity.visualstudio.com/content/problem/1000335/azure-pipelines-trims-leading-and-trailing-rn-from.html

Dont trim whitespace from inputs

---

node/docs/nodeEnvironment.md
node/docs/nodeVersioning.md
node/mock-test.ts
node/package-lock.json
node/package.json
node/test/fakeTasks/node14task/task.json
node/test/mocktests.ts

Also changes the default node version to 14 if we can't find a version

Support node 14 tests

---

node/mock-test.ts
node/package-lock.json
node/package.json

[MockTestRunner] Fixed node version determination

---

azure-pipelines.yml
node/.npmrc

Automatically publish package on CI

---

node/docs/nodeEnvironment.md
node/docs/nodeVersioning.md

Reverted doc changes for node14 handler - since we don't ship it currently with agent.

[Docs] Reverted changes for node 14

---

Localize/loc/de-de/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/de-de/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/es-es/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/es-es/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/fr-fr/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/fr-fr/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/it-IT/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/it-IT/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ja-jp/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ja-jp/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210206032331764 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210206032331764 to Localization

---

Localize/loc/it-IT/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210216210949587 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210216210949587 to Localization

---

Localize/loc/zh-TW/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210222210941733 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210222210941733 to Localization

---

Localize/loc/it-IT/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210318201117554 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210318201117554 to Localization

---

Localize/loc/it-IT/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210323081249940 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210323081249940 to Localization

---

Localize/loc/it-IT/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210323201053260 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210323201053260 to Localization

---

node/package-lock.json
node/package.json

Updated package version to publish a new release of task-lib.

Preparing for release of the 3.1.1 version

---

.github/workflows/autoAssignABTT.yml

Added action to automatically add new issues to the team planning board.

Added Auto assign action

---

node/package-lock.json
node/package.json
node/task.ts

**Issue description:** looks like shell.cp method can throw errors - for this case there is no retry logic.
**How it was fixed:** wrapped these calls by try/catch block also.

Fixed issue with shell.cp retry

---

node/package-lock.json
node/package.json

Forgot to bump in https://github.com/microsoft/azure-pipelines-task-lib/pull/719

Bump package version

---

node/task.ts

This PR fixes review points in [another PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/779) after the one was merged.

Review points fixing for 779 PR

---

node/mock-answer.ts
node/package-lock.json
node/package.json

Related to [issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/621) 
Changed check for null to explicit comparison to avoid zero number being checked as null.

Change implicit check in getResponse to explicit

---

azure-pipelines-steps-node.yml
azure-pipelines-steps-test-build.yml
azure-pipelines.yml

Cherry-pick for a [PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/848)

Update pipeline to include a step for publishing artifacts

---

azure-pipelines.yml

**Description**: Change command to add npm registry
**Testing** No test needed

Fix npm publishing

---

Localize/loc/es-ES/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/fr-FR/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20221105085105779 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20221105085105779 to Localization

---

Localize/loc/de-DE/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/it-IT/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ja-JP/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20221106085044954 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20221106085044954 to Localization

---

azure-pipelines.yml

Fixing the release path in the pipeline for 4th release branch
**Changelog**:
added `release/` in path

Fixed release path

---

azure-pipelines.yml

Fixing the release path in the pipeline for 4th release branch
**Changelog**:
Changed Build.SourceBranchName to Build.SourceBranch to improve branch detection (https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml)

Improvement of the release condition

---

node/package.json

Removing preview from version, version is stable

Removing preview from version

---

azure-pipelines-steps-node.yml
azure-pipelines-steps-test-build.yml
azure-pipelines.yml

Fixing the pipeline for master branch to release 3th version
**Changelog**:
- Cleaned title of steps
- Removed unnecessary steps
- Fixed bug with `cd _build` command: it was wrong order, replaced by correct workingDirector
- Fixed npm token

Pipeline fixing

---

node/README.md

Fixed links to make them clickable on npm https://www.npmjs.com/package/azure-pipelines-task-lib
Related issue: https://github.com/microsoft/azure-pipelines-task-lib/issues/899

Fixed Readme for npm package

---

node/CHANGELOG.md

Added description of version 4.2.0 after merging  [PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/912)

Updated CHANGELOG.md

---

node/package-lock.json
node/package.json

- Bumped qs version with npm audit fix

[Bug 2029503](P2): [Component Governance Alert] - CVE-2022-24999 in qs 6.9.4. Severity: High #4370

---

Localize/loc/de-DE/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/it-IT/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ko-KR/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ru-RU/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20230824085133912 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20230824085133912 to Localization

---

powershell/Docs/ReleaseNotes.md
powershell/package.json

Follow-up to #944
- increased Powershell SDK version
- updated release notes

Increase PS SDK version

---

tasks.schema.json

***Description:*** Add `removalDate` for deprecated tasks into the tasks schema.

Update tasks schema - add `removalDate`

---

Localize/loc/de-DE/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20231019084924530 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20231019084924530 to Localization

---

powershell/package-lock.json

Regens package-lock to address changes from #978

Regen package-lock.json

---

node/lib-mocker.ts
node/mock-run.ts
node/package-lock.json
node/package.json
node/test/fakeModules/fakemodule1.ts
node/test/fakeModules/fakemodule2.ts
node/test/internalhelpertests.ts
node/test/mockertests.ts
node/test/testutil.ts
node/test/tsconfig.json

- Add mockery changes to task-lib version 4
This PR adds mockery to task-lib version 4 and allows to publish from release branch. 
Based on the PRs:
Mockery replacement: https://github.com/microsoft/azure-pipelines-task-lib/pull/968
Allow to publish changes from release branch: https://github.com/microsoft/azure-pipelines-task-lib/pull/969

[release/5.x merging] - Transfer changes from release/5.x branch to master

---

node/package-lock.json
node/package.json
node/task.ts
powershell/VstsTaskSdk/OutFunctions.ps1
powershell/package-lock.json
powershell/package.json

Small fix for the changes in https://github.com/microsoft/azure-pipelines-task-lib/pull/1009
Added an issue source for uncaught exceptions.
Changed the version of npm packages:
node 4.8.0 -> 4.8.1
powershell 0.18.0 -> 0.18.1

Issue source for uncaught exceptions

---

node/internal.ts
node/package-lock.json
node/package.json
node/task.ts
node/test/resulttests.ts
powershell/VstsTaskSdk/OutFunctions.ps1
powershell/package-lock.json
powershell/package.json

Added issue sources for all errors and warnings inside SDKs.
Bump versions:
node 4.8.1 -> 4.8.2
powershell 0.18.1 -> 0.18.2

Add issue sources for all internal issues

---

.github/workflows/autoAssignABTT.yml
.github/workflows/localization-automerge.yml
.github/workflows/stale.yml

**Description**: 
- Added write permissions in gh workflow
**Documentation changes required:** N
**Added unit tests:** N
**Attached related issue:** WI 2140156
**Checklist**:

Update github workflows to avoid issues with GITHUB_TOKEN

---

node/CHANGELOG.md
node/package-lock.json
node/package.json

Bump node lib to publish recent changes #1033
Also corrected changelog

Bump node lib to 4.12.0

---

node/CHANGELOG.md
node/internal.ts
node/package-lock.json
node/package.json

We don't actually need to write debug logs when debug mode is not enabled as agent skips them.
This PR aims to reduce the stdout throughput and to mitigate unexpected issues when the debug mode enabled.
WI: [AB#2180742](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2180742)

Node: Check debug mode for debug logs

---

.npmrc
azure-pipelines-steps-node.yml
node/.npmrc
node/package-lock.json
powershell/.npmrc
powershell/package-lock.json

**Description**: This PR adds **.npmrc** to all packages in the repository to consume packages from the internal feed.
**Related**: [AB#2197030](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2197030)

Migration to CFS

---

tasks.schema.json

**Description:**
The PR adds new Node20 handler in task.json schema
**Related WI** https://github.com/microsoft/azure-pipelines-task-lib/issues/1074

Add node20 handler to task schema

---

node/package-lock.json
node/package.json

Updating version from 5.0.0 to 5.1.0
Updating minor version of task-lib post fixes for copy and remove functionality to publish package.

Minor version update

---

node/task.ts

Add logging for the Agent.Version and improve the error message when the agent version does not meet the minimum required version.
1. Logs the detected Agent.Version using debug(...) for traceability.
1. Enhances the error message to include the actual agent version when it falls below the required minimum.
**Low**/Medium/High
1. Build validation only

Task Lib - Logging Detected Agent Version in AssertAgent - AB#2268162

---

powershell/package-lock.json
powershell/package.json

Upgrading minimatch version to fix MSRC vulnerability issue.
Upgraded mocha as well as it uses vulnerable version of minimatch

Upgrading minimatch version to fix MSRC vulnerability issue
