node/lib/vsotask.ts
node/test/tasklib.ts

variables having multiple dots such as Build.Repository.Uri were not working because of this bug.

Fixing setVariable and getVariable to replace all . or _'s

---

node/lib/vsotask.ts

Description: The PublishTestResults Task's xplat implementation is currently different from windows implementation. Users choice of Run Title and option to not publish result files do not exist in the current xplat implementation.
Solution: Changes have been made for Junit, xunit and nunit to honor users choice of run ttitle and user can now opt out of publishing test attachments.
https://github.com/Microsoft/vso-agent-tasks/pull/954
https://github.com/Microsoft/vso-agent/pull/168
Testing: Manual for now. Appropriate unit tests will be added if required.

Run Title and Publish Test Attachments Changes

---

README.md

badge link had a whitespace between the "]" and the "(" which prevented it from being rendered as a link in npmjs registry

Removed whitespace in build badge link.

---

node/lib/task.ts

Presently Xplat agent doesn't support merging of test results.
With this change, Xplat agent will publish merged test results and all the test files will be published in single archive.

Support Merge Test Results for Xplat Agent

---

powershell/VstsTaskSdk/LocalizationFunctions.ps1

Get-Content does not use UTF8 unless explicitly specified in Japanese PowerShell environment. Specify Encoding UTF8 solves loading localized resource issue.
Closes bug #62

Fix loading Japanese resource failed

---

node/lib/task.ts
node/lib/toolrunner.ts

Need to expose the following methods in task so I can mock them in L0 tests in vsts-tasks
process.cwd(): string;
os.type(): string;
fs.readdirSync(path: string): string[];
Also adding a null check in tool runner so if the tool is not kicked off properly and results in no stdout or stderr, node doesn't just die but instead bubbles up a failure to the offending task.

adding mock hooks & null check in toolrunner

---

node/task.ts

Current order doesn't work with Ant tool. Ant.cmd don't build as expected to be. Ant.bat does that

Change Tool discovery order

---

powershell/VstsTaskSdk/ServerOMFunctions.ps1
powershell/VstsTaskSdk/TraceFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psm1

Soliciting early feedback. I still need to test against Dev14 and tweak the Extended Client function.
Currently, this would reduce client code to load an HTTP client to simply:
```powershell
$projectHttpClient = New-VstsVssHttpClient -TypeName Microsoft.TeamFoundation.Core.WebApi.ProjectHttpClient
$projectHttpClient.GetProjects().GetAwaiter().GetResult()
```

OM functions.

---

node/package.json
node/taskcommand.ts
node/test/commandtests.ts
powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
powershell/package.json

This investigation originally started because of [this](https://github.com/Microsoft/vsts-agent/issues/1100) issue.
The code here doesn't solve that specific issue but we need it anyways. That issue will be solved by a change in DistributedTask.
This change adds escaping for ']' in the node code and ps code. We also weren't escaping the property values in the node code previously so that is added too. The Agent already unescapes property values.

Add escaping of closing bracket character

---

tasks.schema.json

Fixes Microsoft/vsts-tasks#1854

Add task.json schema file

---

node/internal.ts
node/package.json
node/test/loctests.ts

This is in reference to:
#242 Enable importing multiple resource files
I changed resource files to a dictionary for quick access, the key and value are the same (the path).

Allow multiple resource files

---

node/package.json
node/test/dirtests.ts

Update all dependencies to latest version, don't use carat.
There is an issue when updating to latest versions of shelljs that is tracked here #326.

Update dependency versions.

---

README.md
node/README.md
node/mock-answer.ts
node/mock-toolrunner.ts

These are all the commands that are looked up in `MockAnswers` in mock-task and mock-toolrunner.
With this change, we should stop using type assertions to force the `TaskLibAnswers` type when we set up the mocks for our L0 tests.
This will allow test authors to catch commands they think are being mocked but are not.

Update TaskLibAnswers to have all supported commands

---

node/test/toolrunnertests.ts
node/toolrunner.ts

We want to be able to write the output of the first tool to a file in addition to piping it to another tool to simulate something like this: xcodebuild <options> | tee xcodebuild.log | xcpretty. This works but looking for feedback on the approach before adding unit tests.

Add option to pipe to file and another tool

---

node/mock-answer.ts
node/package.json

Forgot to bump the patch version before.
Noticed that I missed a couple of commands that were actually mocked, and so the previous changes were insufficient to stop coercing the `TaskLibAnswer` type in our existing code.  I defined the `MockedCommand` type here so that the compiler will catch all arguments to `getResponse`.

Missed a couple mocked commands.  Bump patch version

---

powershell/Tests/L0/Get-SecureFileName.ps1
powershell/Tests/L0/Get-SecureFileTicket.ps1
powershell/VstsTaskSdk/InputFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psm1

Added two new input functions in PS SDK Get-VstsSecureFileName and Get-VstsSecureFileTicket to match the available operations in Node SDK. For each new cmdlet, there is also a test associated.

Added SecureFile functions in PS SDK

---

tasks.schema.json

Addressing issue: https://github.com/MicrosoftDocs/vsts-docs/issues/549

Adding secureFile input type in task.json scheme

---

powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psm1

Certain logging commands were not implemented in the PS SDK. Added the missing ones as requested by #310

Added missing logging commands

---

tasks.schema.json

There was a missing comma making the document unusable.

Add missing comma

---

node/test/findmatchtests.ts
powershell/Tests/L0/Find-Match.SupportsPathNotFound.ps1
powershell/Tests/L0/Get-FindResult.ReturnsEmptyWhenNotExists.ps1
powershell/VstsTaskSdk/FindFunctions.ps1

The fix I propose here intends to get the same behavior than when using ts `findMatch` function. To illustrate that, I added a unit test in both ts and ps.
More precisely, I pinpoint the difference between ts and ps here: https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L751.

Find-Match in powershell does not support searching a pattern in a path that does not exist

---

powershell/Docs/UsingOM.md

I shared these instructions with someone who is *very* new to ~VSTS~ Azure DevOps and was confused by the title of this doc. The naming/branding change will undoubtedly take a while to get through, but hopefully this little bit helps.

Change reference to VSTS to Azure DevOps

---

tasks.schema.json

maybe the id of the schema should be renamed as well if possible.

rename VSTS to Azure DevOps

---

azure-pipelines.yml

Code page changes seem to have broken csc.exe. I'm investigating further, but this should at least get them up and running again.
Fixes #492

Get tests running again

---

node/docs/releases.md

@bryanmacfarlane Would probably be good to release once this is in.

Update release notes for 2.8.0

---

tasks.schema.json

It is required for some tools (such as json2ts) to work properly. 
Other similar pattern have the type specified so I assume this has just been forgotten.

Add missing "type" on connectService string pattern

---

README.md

Add a note on ARM and x86 support, as v2.141.0 breaks a the implicit assumption that tasks can only run on x64.

Include a note on ARM and x86 agent support

---

node/mock-task.ts
node/package-lock.json
node/package.json

Add a mock for `setSecret`. Currently unit tests fail if you try to use `setSecret` in your task.

Add setSecret to mock-task.

---

node/mock-test.ts

Right now, if you set the input for one test run that carries over to the next one. This disables that behavior
Fixes #471

Clean environment after running mocks

---

node/package-lock.json
node/package.json
node/task.ts

Right now, if there are too many childItems this exceeds the stack call size. This fixes this problem by pushing them one by one instead of with the `…` operator.
Fixes #408

Enable large numbers of children to be pushed in find

---

README.md

Update link to vsts-task to use the newer repo name of vsts-tasks, the azure-pipelines-tasks

Update link to vsts-task to use the newer name of azure-pipelines-tasks

---

node/package-lock.json
node/package.json
node/task.ts

Remove unnecessary logging that results in `SYSTEMVSSCONNECTION exists true` spew in build output.

Remove endpoint authorization non-debug logging (SYSTEMVSSCONNECTION exists true)

---

node/package-lock.json
node/package.json
node/test/toolrunnertests.ts
node/toolrunner.ts

Reported as an issue in the agent:
https://github.com/microsoft/azure-pipelines-agent/issues/2242

Fixed an issue where output from command without newline was dropped

---

node/taskcommand.ts
node/test/commandtests.ts

This will allow users to pass the literal value `%0A` for example and have it get correctly escaped. See #542 for context
Fixes #542

Escape % signs

---

node/internal.ts

Right now, if `check` is true we get the result of `_which(tool, false)` and then don't use that result if the tool is found. We should just short circuit there if the tool is found, rather than basically performing the `_which` an extra time

Dont perform which twice when check is true

---

node/test/findmatchtests.ts

Hi! I was investigating a customer issue over at App Center that required some debugging with findMatch. While the error ended up not being related to this task, I did notice a missing test assertion while I was looking into it.
I think this is just an oversight, so here's a quick PR to add it!

Add missing assertion in single pattern findMatch tests

---

powershell/Docs/Consuming.md

RIght now, we recommend putting the entry PS1 script at the root, but you don't _have_ to do that. This clarifies what you should do if you don't want to do that for some reason

Slight doc clarity nit

---

node/toolrunner.ts

In fact the handling of these properties already allows for them to be undefined/null. But the annotations didn't indicate this.
Since the entire options object was optional, having a couple properties on it *not* optional makes it hard to start supplying *any* options since the user must figure out what values to supply for these two properties to get equivalent behavior, in order to set some *other* option on the object.

Annotate outStream and errStream as optional

---

node/toolrunner.ts

While it doesn't make any sense, the typings for `process.env` is:
```ts
interface ProcessEnv {
[key: string]: string | undefined;
}
```
So assigning `process.env` to `IExecSyncOptions.env` in typescript with all typings turned on produces compiler errors (at least when strict null checking is applied).
Without this simple typings adjustment, the following workaround in user code is required:
```ts
function GetFilteredEnv() {
const result = {};
const block = process.env;
for (const key in block) {
if (block.hasOwnProperty(key)) {
const value = block[key];
if (value !== undefined) {
result[key] = value;
}
}
}
return result;
}
let options: IExecSyncOptions = { env: GetFilteredEnv() };
```
But with this change it's as simple as:
```ts
let options: IExecSyncOptions = { env: process.env };
``` …

Allow undefined env var values

---

node/docs/samples/toolrunner.src

The previous code example had `tr.exec()` on line 8. However, it should be `atool.exec()`.

Fixed documentation for tr.exec()

---

node/package-lock.json
node/package.json
node/toolrunner.ts

Added shell property to IExecOptions to allow this property to be specified in pipelines tasks code. This option allows handling variables in command strings.
Related to the [issue.](https://github.com/microsoft/azure-pipelines-tasks/issues/12848)
These changes are required for the [PR in azure-pipelines-tasks repository](https://github.com/microsoft/azure-pipelines-tasks/pull/12880).

Added shell property to IExecOptions

---

node/task.ts
node/test/inputtests.ts

Changing the type for `delimiter` to `string | Regexp` in `getDelimitedInput` adds support for multiple delimiters. Supporting multiple delimiters would allow https://github.com/microsoft/azure-pipelines-tasks to which is needed for https://github.com/microsoft/azure-pipelines-tasks/issues/12927 by passing a regular expression to `getDelimitedInput` instead of naively using `split` which breaks when there are no Git tags.

Permit getDelimitedInput to split on either a string or a Regexp

---

node/package-lock.json
node/package.json
node/test/toolrunnertests.ts
node/toolrunner.ts

Enhancement for #637 
Required to fix issue [#12848](https://github.com/microsoft/azure-pipelines-tasks/issues/12848).
Required for PR [#13099](https://github.com/microsoft/azure-pipelines-tasks/pull/13099)
Applied enhancement for `shell` option to wrap a tool path and arguments with double quotes to ensure that command is handled correctly if it is executed inside shell. The path and arguments are wrapped only if `shell` property of `IExecOptions` object set to true. 
Added tests.

[ToolRunner] Enhanced 'shell' execution option

---

node/package-lock.json
node/package.json
node/toolrunner.ts

These types are what stdout and stderr are, not stream.Writeable. New TS versions are complaining about type mismatches

Fix stdout/stderr types

---

node/package-lock.json
node/package.json
node/toolrunner.ts

This PR is a part of solution for [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11468) in azure-pipelines-tasks repo. 
Customer has a problem with getting of SIGINT signals inside his build script that contains some additional logic when pipeline run cancellation  happens. This PR should add support of sending SIGINT signals to child processes to get them the ability to perform a number of operations before closing the process in SIGINT handler.

Add support for killing child processes with SIGINT signal

---

node/internal.ts
node/package-lock.json
node/package.json

Added parameter to `setResourcePath` method to add posibility to disable warnings thrown
Related issue:
[#274](https://github.com/microsoft/build-task-team/issues/274)

Added parameter to setResourcePath to add posibility to disable warnings thrown

---

node/package-lock.json
node/package.json
node/task.ts

Parent issue: [364](https://github.com/microsoft/build-task-team/issues/364)
**Description**
We get the following error during the compilation of XcodeV5 task in _azure-pipelines-tasks_ repo using a newer version of _azure-pipelines-task-lib_:
> Argument of type 'string[]' is not assignable to parameter of type 'string'.
`mathcingTestResultsFiles` has `string[]` type [here](https://github.com/microsoft/azure-pipelines-tasks/blob/1538fd6fdb8efd93539b7fe65b00df900d963c1a/Tasks/XcodeV5/postxcode.ts#L38) as it's the result of `findMatch` [function](https://github.com/microsoft/azure-pipelines-task-lib/blob/cf18a238d0ec500d8e8e86b2ff74f901cc92aec2/node/task.ts#L1501). There are several more tasks with the same behavior in the _azure-pipelines-tasks_ .
So we can use `string[]` type (instead of …

Change type of the resultFiles parameter of publish method in TestPublisher class

---

node/package-lock.json
node/package.json
node/task.ts
node/test/commandtests.ts
node/test/inputtests.ts

This PR resolves #688 by extending the `setVariable` functionality to support output variables.
As suggested by @chris-codeflow, this is as simple as adding the [`isOutput=true`](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-a-multi-job-output-variable) property to the `task.setvariable` logging command.
The change is backwards compatible - it does *not* change the signature of `setVariable`.  Rather it adds a new final parameter named `isOutput`.  When `true` the command generated will feature `isOutput=true`.
Consider: 
```ts
tl.setVariable('foo', 'bar', false, true)
```
This would generate the following:
`##vso[task.setvariable variable=foo;isOutput=true;]bar`
I've added a couple of tests.  However it's been a little …

Extend setVariable to allow 'output' variables to be created

---

node/task.ts
node/test/commandtests.ts
node/test/inputtests.ts

This is a follow on to #691 which applies the changes there to the `release/3.x` branch as requested by @damccorm

Extend setVariable to allow 'output' variables to be created: apply changes to release/3.x branch

---

node/package-lock.json
node/package.json
node/task.ts

Updated publish methods' to keep it compatible with tasks using different argument types.
Related issue (internal): [#356](https://github.com/microsoft/build-task-team/issues/356)
The approach was chosen taking the following case into consideration:
- If an empty string is passed to `publish` method of `CodeCoveragePublisher` class as `additionalCodeCoverageFiles` argument we would get the following result:
`##vso[codecoverage.publish]`
- If we try to pass an empty array we would get:
`##vso[codecoverage.publish additionalcodecoveragefiles=;]`
The approach is to pass a string in any case since it's expected by the `TaskCommand` class.

Updated publish methods' to keep it compatible

---

tasks.schema.json

Example:
```json
{
"restrictions": {
"commands": {
"mode": "restricted"
},
"settableVariables": {
"allowed": [ "myVar", "otherVar" ]
}
}
}
```

Update schema for task restrictions

---

node/Strings/resources.resjson/en-US/resources.resjson
node/docs/azure-pipelines-task-lib.md
node/lib.json
node/package-lock.json
node/package.json
node/task.ts

Added retry logic to the cp() method to avoid intermittent build fails.
Related work item: [#757](https://github.com/microsoft/build-task-team/issues/757)
[Those changes were also introduced for the 2.x release.](https://github.com/microsoft/azure-pipelines-task-lib/pull/707)
Test examples (these changes are tested with CopyFiles task running on Node 10):
[Successful build](https://dev.azure.com/v-egbryz/TestProject/_build/results?buildId=1618&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f0a8695-ceaa-5eb2-5ab8-df326b6acd5f)
[Failed build with retryCount set to 2.](https://dev.azure.com/v-egbryz/TestProject/_build/results?buildId=1616&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f0a8695-ceaa-5eb2-5ab8-df326b6acd5f&l=16)
[Failed build with retryCount set to 2 …

[preview] Added retry logic to the cp() method

---

node/Strings/resources.resjson/en-US/resources.resjson
node/docs/azure-pipelines-task-lib.md
node/lib.json
node/package-lock.json
node/package.json
node/task.ts

Added retry logic to the cp() method to avoid intermittent build fails.
Related work item: [#757](https://github.com/microsoft/build-task-team/issues/757)
Test examples:
[Failed build with retryCount set to 2.](https://dev.azure.com/v-egbryz/TestProject/_build/results?buildId=1614&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f0a8695-ceaa-5eb2-5ab8-df326b6acd5f&l=19)
[Failed build with retryCount set to 2 (debug)](https://dev.azure.com/v-egbryz/TestProject/_build/results?buildId=1615&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f0a8695-ceaa-5eb2-5ab8-df326b6acd5f)
[build with retryCount set to 2 (debug, continue on error allowed)](https://dev.azure.com/v-egbryz/TestProject/_build/results?buildId=1613&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f0a8695-ceaa-5eb2-5ab8-df …

Added retry logic to the cp() method

---

open-pullrequest.ps1

Added a script that allows opening a PR to the master branch. Is used in the localization pipeline introduced with [this PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/715).

Added PR opening script

---

Localize/localize-pipeline.yml
open-pullrequest.ps1

**Task name**: Localization pipeline definition
**Description**: 
Added schedule trigger to run the localization pipeline on the third week of a sprint on Mondays at 8 a.m. UTC,
Added Slack notifications about successful and failed builds.
Added a script that automatically bumps tasks and common packages versions.
Added a script that creates a PR to the master branch with localization updates.
The pipeline is going to have the following flow:
Checkout Localization branch -> merge master into Localization and push changes -> OneLocBuild task gathers localization strings and commits them (auto-merge a PR) to the Localization -> create a new branch with localization updates -> open a PR to the master branch.
**Documentation changes required:** No
**Added unit tests:** No
**Attached related …

Applied enhancements for the localization pipeline

---

Localize/loc/ko-KR/node/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/node/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210317201528773 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20210317201528773 to Localization

---

node/taskcommand.ts
node/test/commandtests.ts

We switched this to %AZP25 in the agent repo and turned it on a month ago - https://github.com/microsoft/azure-pipelines-agent/pull/3303
We should make that switch in the task-lib as well now so that when we encode values they automatically get decoded by the agent

Update to use agent-supported version of escaping

---

node/buildutils.js
node/mock-test.ts

The existing tests fail completely without this change, if you try to run them where nodejs.org is not visible (e.g. behind a corporate proxy).
With this change the tests all pass, assuming you set `TASK_NODE_URL` to a mirror URL.
Closes issue #718

Allow mirror URL to be set for NodeJS downloads

---

node/package-lock.json
node/package.json
node/test/toolrunnertests.ts
node/toolrunner.ts

fix bug with  escaped quotes in toolrunner _argStringToArray
for issue [#648 ](https://github.com/microsoft/azure-pipelines-task-lib/issues/648)
1. If we try passing quotes as a value even that is being eaten up by task-lib
Input: `-- TestRunParameters.Parameter(name=paramName,value=argwith"aquote)`
Output `-- TestRunParameters.Parameter(name=paramName,value=argwithaquote)`
2. If we **use backslash** then the quote doesn't is eaten up.
Input: `-- TestRunParameters.Parameter(name=paramName,value=argwith\"aquote)`
Output `-- TestRunParameters.Parameter(name=paramName,value=argwith"aquote)`
3. If we **use backslash** then the quote doesn't is eaten up.
Input: ` -- TestRunParameters.Parameter(name=\"EdiStagingFunctionsKey\",value=\"key2\")`
Output: …

fix bug with escaped quotes in toolrunner _argStringToArray

---

node/package-lock.json
node/package.json
node/task.ts

**Description**: occasionally the `find` function fails with the error `Failed find: ENOENT: no such file or directory`. The reason is that the `fs.lstatSync` method applies to a file that already was deleted. So we should check a file presence and skip it if it does not exist.
**Changelog**: `node/task.ts` — the `find` function — checking a file presence added.
[Related issue](https://github.com/microsoft/azure-pipelines-tasks/issues/14816)

Skipping the file if it was not found

---

node/package-lock.json
node/package.json
node/task.ts

Reverts microsoft/azure-pipelines-task-lib#774
Changes in [this pull request](https://github.com/microsoft/azure-pipelines-task-lib/pull/774) affected the CI for Linux and macOS (Dir Operation Tests) in spite of manual testing passed successfully so we should revert it and investigate why the checks fail.

Revert "Skipping the file if it was not found"

---

node/test/toolrunnertests.ts

**Description:** In the test C# code we use Console.WriteLine() function in the loop. This function can trigger one common "stdout" event with whole output or "stdout" events on each call. 
**Description of fix:** Concat outputs from test tool on every "stdout" event to get whole output.

Fix getting tool output in the CI test

---

node/package-lock.json
node/package.json

**Description**: 
We need to bump up the task lib version to publish recent changes
**Changes**:
- Updated package patch version in `node/package.json` and `package-lock.json` files

Bump up task lib patch version to 3.1.7

---

node/docs/azure-pipelines-task-lib.md
node/package-lock.json
node/package.json
node/task.ts

Fix documentation, comment and condition for getEndpointAuthorization function
The condition was changed because **aval** has type string | undefined, so its value will probably never be null and it will be better to use !!aval for more strong verification, it will allow us to check the empty string also.
related issue #775

Fix documentation, comment and condition for getEndpointAuthorization function

---

Localize/localize-pipeline.yml
open-pullrequest.ps1
send-notifications.ps1

**IMPORTANT - The PR must be completed with PR https://github.com/microsoft/azure-pipelines-task-lib/pull/817 at the same time.**
---
Move notifications about Task-lib Localization PR from Slack to MS Teams. Content of notifications was updated.

Move notifications about Task-lib Localization PR from Slack to MS Teams - Part 1

---

node/docs/azure-pipelines-task-lib.md

Fixed out of date documentation.
Related issue: https://github.com/microsoft/azure-pipelines-task-lib/issues/824

Fix return types for input functions in documentation

---

node/docs/azure-pipelines-task-lib.json
node/docs/azure-pipelines-task-lib.md
node/docs/docs.json
node/mock-task.ts
node/task.ts
node/test/inputtests.ts

Return the value instead of the value or undefined.
getInputRequired
getPathInputRequired
getEndpointUrlRequired
getEndpointDataParameterRequired
getEndpointAuthorizationSchemeRequired
getEndpointAuthorizationParameterRequired

Added new required functions

---

node/package-lock.json
node/package.json

We need to bump up the task lib version to publish recent changes ( Added new required functions https://github.com/microsoft/azure-pipelines-task-lib/pull/827)
Updated package patch version in ```node/package.json``` and ```package-lock.json``` files

Bump up task lib patch version to 3.2.1

---

node/docs/proxy.md
node/package-lock.json
node/package.json
node/task.ts
node/test/gethttpproxytests.ts
node/test/tsconfig.json

Added full proxy URL (http://user:password@host) for the getHttpProxyMethod 
And cover this method with the unit tests.

added formatted proxy URL

---

node/package-lock.json
node/package.json

Updated package minimatch from 3.0.4 to version 3.0.5.
Related issue: https://github.com/microsoft/azure-pipelines-task-lib/issues/832

Update minimatch to version 3.0.5 to fix vulnerability

---

CONTRIBUTING.md

Since at the moment there is active development in two branches, master and releases/4.x, it is necessary to make a note about this
- Updated CONTRIBUTING.md

Update contributing.md according to the current state

---

node/docs/minagent.md
node/docs/nodeEnvironment.md
node/docs/nodeVersioning.md

To add information about the Node 16 handler, the documentation needs to be updated.
- Updated minagent.md
- Updated nodeEnvironment.md
- Updated nodeVersioning.md

Updated documentation

---

node/mock-test.ts
node/test/fakeTasks/node16task/task.json
node/test/mocktests.ts
tasks.schema.json

Node16 must be specified as a valid property in `task.schema.json`.
- Added Node16 to `task.schema.json`
- Added MockTestRunner with Node16

Added node16 to task.schema.json

---

node/package-lock.json
node/package.json

This PR increases the version of task-lib to 4.0.1-preview. The previous [PR](https://github.com/microsoft/azure-pipelines-task-lib/pull/852) did not update the version so it will be done here
No testing need

Bump version

---

node/docs/azure-pipelines-task-lib.json
node/docs/azure-pipelines-task-lib.md
node/docs/docs.json
node/mock-answer.ts
node/mock-task.ts
node/task.ts

Added export function getAgentMode for getting the agent hosted type.
It works throw Agent.CloudId property.
**Changelog**:
Function getAgentMode added to task
Function getAgentMode added to mock
**Documentation changes required**: Yes
Added unit tests: No
**Attached related issue**: Link to PR in the issue

Enable task authors to determine whether the task is running on a hosted agent, or not.

---

node/toolrunner.ts

The max buffer was limited in the higher node version. We have to increase it manually.
[Related issue](https://github.com/microsoft/build-task-team/issues/3588)

fix ToolRunner - _getSpawnSyncOptions

---

node/package-lock.json
node/package.json

Upgraded versions of mocha and mockery due to vulnerabilities
**Changelog**:
- mockery version bumped up from 1.7.0 to 2.1.0
- mocha version bumped up from 5.2.0 to 9.2.2
- types/mocha version bumped up from 5.0.0 to 5.2.7
- bumped up version of library
**Documentation changes required**: No
**Added unit tests**: No
**Attached related issue**: https://github.com/microsoft/azure-pipelines-task-lib/issues/874

Updated mockery and mocha because of vulnerabilities

---

powershell/VstsTaskSdk/LegacyFindFunctions.ps1
powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson

The only place this localized string used is here:
https://github.com/microsoft/azure-pipelines-task-lib/blob/5adadaedd70e68a4130f339e0faf8b8a9a72d273/powershell/VstsTaskSdk/LegacyFindFunctions.ps1#L134-L137
In real world, the error looks like this 
```
##[error]Invalid pattern: 'C:\__w\1\s\src\Application\pkg\Release\'
```
Which is too vague to make it possible to troubleshoot without finding and looking into the source code. I ran into this error here: https://github.com/microsoft/azure-pipelines-tasks/issues/17106.
This PR includes:
1. improving the error message. 
2. using `EndsWith()` instead of `$str[$str,Legth -1]` for readability
However, what doesn't include:
1. I didn't rename the placeholder
2. nor updated the localizations
Please let me know if I should do the former and …

Updated PSLIB_InvalidPattern0 to be more readable

---

powershell/VstsTaskSdk/Strings/resources.resjson/de-de/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/es-es/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/fr-fr/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/it-IT/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ja-jp/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ko-KR/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ru-RU/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-CN/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-TW/resources.resjson

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/ceLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 10947: Build ID 18673037

---

powershell/VstsTaskSdk/Strings/resources.resjson/de-de/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/es-es/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/fr-fr/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/it-IT/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ja-jp/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ko-KR/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ru-RU/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-CN/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-TW/resources.resjson

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/ceLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 10947: Build ID 18697074

---

azure-pipelines-steps-node.yml
azure-pipelines-steps-test-build.yml
azure-pipelines.yml
node/package.json

Fixing the pipeline
**Changelog**:
- Cleaned title of steps
- Removed unnecessary steps
- Fixed bug with `cd _build` command: it was wrong order, replaced by correct workingDirector
- Fixed npm token

Pipeline fixing

---

node/package-lock.json
node/package.json
node/task.ts

The main problem is that when we reject Promises, Node10 and Node16 behaviour is different.
For Node 10, when a promise was rejected without a .catch block will be emitted only [unhandledRejection](https://nodejs.org/docs/latest-v10.x/api/process.html#process_event_unhandledrejection)
For Node 16, when a promise was rejected without a .catch block will be emitted [unhandledRejection](https://nodejs.org/docs/latest-v16.x/api/process.html#event-unhandledrejection) first (if exists), and [uncaughtException](https://nodejs.org/docs/latest-v16.x/api/process.html#event-uncaughtexception) at the end.
In azure-pipelines-task-lib we handle all [uncaughtExceptions](https://github.com/microsoft/azure-pipelines-task-lib/blob/master/node/task.ts#L106) and set TaskResult.Failed.
So when we use node16 …

Added unhandledRejection event

---

node/CHANGELOG.md
node/package-lock.json
node/package.json
node/toolrunner.ts

Described types for `argIf` `ToolRunner` method.

Described types for `argIf`

---

CONTRIBUTING.md

Since task lib v4 already in master, we should remove note about cherry-picking to releases/4.x branch

Remove note about v4 task lib status

---

azure-pipelines.yml
node/test/dirtests.ts
node/test/toolrunnertests.ts

***Description:*** We have to update the Ubuntu image used in the CI since `18.04` will be removed on April 1st.
The path to the `ls` tool has been changed from `/bin/ls` to `/usr/bin/ls` for Ubuntu.
A test to remove a non-empty directory with a locked file inside has been updated as well since such a directory can be removed starting from `windows-2022`.

Update images in the CI

---

node/CHANGELOG.md
node/mock-task.ts
node/package-lock.json
node/package.json
node/task.ts
node/test/inputtests.ts

Add helper to get feature flags for tasks and common packages from env variables.

Add `getBoolFeatureFlag`

---

node/task.ts

Added overload signature.
When the result argument is TaskResult.Succeeded so the message can be optional
[Related issue](https://github.com/microsoft/azure-pipelines-task-lib/issues/940)

Added overload signature for setResult

---

Localize/loc/es-ES/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/fr-FR/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/ja-JP/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-CN/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl
Localize/loc/zh-TW/powershell/VstsTaskSdk/Strings/resources.resjson/en-US/resources.resjson.lcl

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20230823085002328 to Localization with localized lcls

LEGO: Pull request from lego/hb_a4aa9cc4-603b-418e-91f1-700184175625_20230823085002328 to Localization

---

node/lib-mocker.ts
node/mock-run.ts
node/package-lock.json
node/package.json
node/test/fakeModules/fakemodule1.ts
node/test/fakeModules/fakemodule2.ts
node/test/internalhelpertests.ts
node/test/mockertests.ts
node/test/testutil.ts
node/test/tsconfig.json

- Replaced Mockery test-lib since it has vulnerabilities and is no longer maintained
- Replaced with self-written adapter inspired by mockery for backward compatibility with tasks.
- All methods which are not used in the tasks are not implemented since they shouldn't be used separately from toolrunner.
- Added unit Tests
- Task-Lib version was bumped to 5.0.0-preview
- The lib was fully tested with all node-based tasks from azure-pipelines-task-lib repository

[Mockery replacement] - Replaced mockery with similar adapter

---

azure-pipelines.yml

Since we started to use release branch for mockery replacement changes and node20 migration we need to allow publish the changes from releases/ branches

Allow to publish changes from release branch

---

powershell/VstsTaskSdk/Strings/resources.resjson/de-DE/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/es-ES/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/fr-FR/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/it-IT/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ja-JP/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ko-KR/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/ru-RU/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-CN/resources.resjson
powershell/VstsTaskSdk/Strings/resources.resjson/zh-TW/resources.resjson

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 10947: Build ID 22418181

---

node/CHANGELOG.md
node/Strings/resources.resjson/en-US/resources.resjson
node/lib.json
node/mock-answer.ts
node/mock-task.ts
node/package-lock.json
node/package.json
node/task.ts

This PR adds new function `getNodeMajorVersion` to tasks.ts.
**To do:**

Introduce tl.getNodeMajorVersion

---

node/Strings/resources.resjson/de-DE/resources.resjson
node/Strings/resources.resjson/es-ES/resources.resjson
node/Strings/resources.resjson/fr-FR/resources.resjson
node/Strings/resources.resjson/it-IT/resources.resjson
node/Strings/resources.resjson/ja-JP/resources.resjson
node/Strings/resources.resjson/ko-KR/resources.resjson
node/Strings/resources.resjson/ru-RU/resources.resjson
node/Strings/resources.resjson/zh-CN/resources.resjson
node/Strings/resources.resjson/zh-TW/resources.resjson

This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.

Localized file check-in by OneLocBuild Task: Build definition ID 10947: Build ID 23093005

---

node/CHANGELOG.md

- Added info about task-lib 4.7.0
- Sorted the changelog in reverse chronological order

[Changelog] - add info about task-lib 4.7.0

---

node/internal.ts
node/package-lock.json
node/package.json
node/task.ts
powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psd1
powershell/VstsTaskSdk/VstsTaskSdk.psm1
powershell/package-lock.json
powershell/package.json

Added support for the optional 'source' property to the error/warning functions to distinguish internal task issues and the issues that occur because of incorrect customer actions (for example, the invalid user script).
Testing: local dev environment with additional changes in PowerShell, Bash and CmdLine tasks.
Changed the version of npm packages:
node 4.7.0 -> 4.8.0
powershell 0.17.0 -> 0.18.0

Add support for the optional 'source' property to the error/warning functions

---

node/internal.ts
node/mock-task.ts
node/package-lock.json
node/package.json
node/task.ts
node/test/internalhelpertests.ts
node/test/resulttests.ts

There were several cases when we observed sensitive data (such as passwords) leakage through `task.setResult` function. To prevent such behavior this PR introduces `setSanitizedResult` function that truncates the passed message before first occurrence of well known sensitive keyword. For more details see the original [incident](https://portal.microsofticm.com/imp/v3/incidents/incident/466877337/summary) or its [repair item](https://mseng.visualstudio.com/AzureDevOps/_workitems/edit/2147925).

Add setSanitizedResult function

---

node/CHANGELOG.md
node/internal.ts
node/package-lock.json
node/package.json
node/test/taskissuecommandtests.ts
powershell/Docs/ReleaseNotes.md
powershell/Tests/L0/Write-LoggingCommand.WritesAuditToIssues.ps1
powershell/Tests/L0/Write-LoggingCommand.WritesTaskIssue.ps1
powershell/Tests/L0/Write-LoggingCommand.WritesTaskIssueWithCorrelationId.ps1
powershell/Tests/lib/TestHelpersModule/PublicFunctions.ps1
powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
powershell/VstsTaskSdk/VstsTaskSdk.psm1
powershell/package-lock.json
powershell/package.json

Added audit action data property for issues.
Also, fixed order of properties for `task.issue` log command
WI: [AB#2123720](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2123720)

Add audit action for task.issue

---

node/buildutils.js

On Linux and MacOs, we download `.tar.gz` archives rather than `.zip` for Windows. `adm-zip` package does not support the `.tar.gz` and throws the error:
```text
Invalid or unsupported zip format. No END header found
```
Here I used the pre-installed `tar` tool to unpack node for unix systems
WI: [AB#2190598](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2190598)

Use tar tool for .tar.gz node.js archives

---

node/CHANGELOG.md
node/package-lock.json
node/package.json

**Changes**: This PR updates azure-pipelines-task-lib module to 4.17.0.
Additionally, changes from v4.14.0 and v4.17.0 have been added to CHANGELOG.md

Release 4.17.0

---

node/CHANGELOG.md
node/package-lock.json
node/package.json
node/toolrunner.ts

Sometimes 'exit' event raises when stdout is not yet flushed leading to case when debug log injected between tool output chunks.
This PR moves all debug logs related to process 'exit' and 'close' events to the place where stdout should be already closed.
WI: [AB#2180742](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2180742)

Fix debug logs inside user commands

---

node/make.js
node/task.ts

For local builds, use tsc from modules (via npx)

Fix for checks not failing on compilation error

---

node/CHANGELOG.md
node/package-lock.json
node/package.json
node/task.ts

Issue #1069
We already subscribe to debug events in the [tool function](https://github.com/microsoft/azure-pipelines-task-lib/blob/89c945c168e9bee843b3d87a528f2cf2beced0ef/node/task.ts#L1593-L1600)
So no need to do this twice as it leads to debug logs duplication.
Before:
```txt
##vso[task.debug]exec tool: C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
##vso[task.debug]exec tool: C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
##vso[task.debug]arguments:
##vso[task.debug]arguments:
##vso[task.debug]   -c
##vso[task.debug]   -c
##vso[task.debug]   echo hello
##vso[task.debug]   echo hello
[command]C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -c "echo hello"
hello
##vso[task.debug]Process exited with code 0 and signal null for tool …
```

Remove duplicate debug logs when using `task.exec*` wrappers

---

powershell/VstsTaskSdk/ToolFunctions.ps1
powershell/package-lock.json
powershell/package.json

Recently we faced [the issue](https://github.com/microsoft/azure-pipelines-tasks/issues/19781) where exit code for process was not set, and it was the root cause of pipeline failures.
I noticed that PowerShell could behave incorrectly if we manage the process using .NET API directly (for instance, we had to cache the process handle to obtain the status code as a workaround. please check https://stackoverflow.com/a/23797762)
Even though I didn't manage to reproduce the issue specified at the beginning by myself. I suppose that native PS cmdlets will help to fix it. 
WI: [AB#2222447](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2222447)
Testing: manual, unit tests
Other changes: Changed ts version to fix the unit tests

Fix process invocation for PowerShell handler

---

node/task.ts

Fixes the CodeQL vulnerability - Unsafe shell command constructed from library input (in node/task.ts)
**Original Code:** The original code constructs a shell command by concatenating the inputPath variable directly into the command string. This can be exploited if the inputPath contains special characters or malicious input.
```childProcess.execSync(`rd /s /q "${inputPath}"`);```
```childProcess.execSync(`del /f /a "${inputPath}"`);```
**Fixed Code:** The fixed code uses childProcess.execFileSync to pass the command and its arguments separately, which prevents the shell from interpreting the input.
```childProcess.execFileSync("cmd.exe", ["/c", "rd", "/s", "/q", inputPath]);```
```childProcess.execFileSync("cmd.exe", ["/c", "del", "/f", "/a", inputPath]);```
This approach ensures that …

Fix - [CodeQL:Warning]: SM03609: Unsafe shell command constructed from library input (in node/task.ts)- AB#2236216

---

node/internal.ts

The suppression is needed as this is genuine scenario based on [OWASP](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#hashing-vs-encryption). This is approved by internal security team as well.

Suppressing CODEQL warning

---

node/task.ts
node/test/ls.ts

Fix to have relative path with respect to base directory in output of LS command
**1. Why is this change being made?**
- Changes made to output relative path of listed files/folders in output of LS command to maintain same behavior as output by shellJs
**2. What has been changed?**
- Absolute path changes to relative with respect to base directory
**3. How was this tested?**
- Tested by running the task on pipeline to ensure installation works as expected.
- Pipeline run link: https://dev.azure.com/rishabhmalikOrg/Test%20Project/_build/results?buildId=437&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d6b0b499-3d6b-51f2-b264-9b9f875515b5
- Output with original ShellJS implementation: https://dev.azure.com/rishabhmalikOrg/Test%20Project/_build/results?buildId=439&view=logs&j=12f1170f-54 …

Fix to have relative path with respect to base directory in output of LS command

---

node/package-lock.json
node/package.json
node/task.ts
node/test/cp.ts

**Problem Being Solved:**
- The original code failed on Ubuntu when handling relative symbolic links
- Windows typically uses absolute paths in symlinks, while Linux often uses relative paths
- When copying files with relative symlinks, the code would fail with ENOENT (file not found) errors
**Why Original Code Failed:**
`source = fs.readlinkSync(source);`
- This simply reads the raw symlink target path
- On Linux with relative symlinks (e.g., ../file.txt), this raw path would be used directly
- The relative path would be evaluated from the wrong working directory context
**How New Code Fixes It:**
- Gets the directory containing the symlink using `path.dirname(source)`
- Uses `path.resolve()` to convert relative paths to absolute paths
- Resolves the symlink target relative to its …

Fix: Symlink Resolution for Cross-Platform Copy Operations

---

node/task.ts

**Problem**
The current code uses Array.flat() which is only available in Node.js versions >= 12. This causes compatibility issues when running on older Node.js versions that are still supported by Azure Pipelines agents.
**Changes**
- Added new flattenArray() helper function to recursively flatten nested arrays
- Removed usage of Array.flat() method
**Github Issue Link:** https://github.com/microsoft/azure-pipelines-tasks/issues/21048
**Testing**
Tested with already existing unit tests having multiple paths as input to LS function in an array.

Replace Array.flat() with custom flattenArray() function for Node.js compatibility

---

node/package-lock.json
node/package.json
node/task.ts
node/test/ls.ts

Explanation of the fix we implemented in the `ls` function for the single file input issue:
- When providing a single file as input to `ls()`, it was returning an empty string because the relative path calculation was comparing the file path against itself.
- We separated the handling of files and directories into two phases:
```typescript
// Phase 1: Early file handling
if (stats.isFile()) {
// For files, just add the basename to results array
const fileName = path.basename(pathEntry);
results.push(fileName);
} else {
// Keep directories for later processing
remainingPaths.push(pathEntry);
}
```
1. Files are processed first, before any directory traversal
2. For files, we simply extract and store the basename
3. Only directories continue to the existing relative path calculation logic
1. …

LS function fix for single file input
